# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "media_files", :force => true do |t|
    t.column "relative_path", :string, :default => "", :null => false
    t.column "repository_id", :integer, :default => 0, :null => false
    t.column "created_at", :datetime, :null => false
    t.column "updated_at", :datetime, :null => false
  end

  create_table "playlists", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "name", :string, :default => "", :null => false
  end

  create_table "playlists_items", :force => true do |t|
    t.column "playlist_id", :integer, :default => 0, :null => false
    t.column "media_file_id", :integer, :default => 0, :null => false
    t.column "position", :integer, :default => 0, :null => false
  end

  create_table "repositories", :force => true do |t|
    t.column "path", :string, :default => "", :null => false
    t.column "name", :string, :default => "", :null => false
  end

  create_table "users", :force => true do |t|
    t.column "login", :string
    t.column "email", :string
    t.column "crypted_password", :string, :limit => 40
    t.column "salt", :string, :limit => 40
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "remember_token", :string
    t.column "remember_token_expires_at", :datetime
  end

end
